### ISSUE TITLE
YAML configuration not registered/explained

### ISSUE THREAD

**Issue by mbrodala** [kitzberger/form-mailtext#1]
The `MailtextFormSetup.yaml` provided by this package is not registered by default and there is no explanation how to do so.

Thus I'd suggest to either add a short example to the `README` ([reference](https://docs.typo3.org/c/typo3/cms-form/10.4/en-us/I/Concepts/Configuration/Index.html#yaml-registration)) or directly add a [`ext_typoscript_setup.typoscript`](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/FilesAndLocations/Index.html#ext-typoscript-setup-typoscript) which takes care of this.

**Comment by kitzberger** [comment]
@mbrodala, thanks for reaching out! I need to check the extension again but I think that inclusion is done within `ext_localconf.php` already, isnt' it?

https://github.com/kitzberger/form-mailtext/blob/master/ext_localconf.php

**Comment by mbrodala** [comment]
You are right, this should just work :tm:

Since I only forwarded this from a Slack discussion I've asked the original user to comment here.

**Comment by kitzberger** [comment]
@mbrodala, I've recently changed the inclusion of the TS to a `ext_typoscript_setup.typoscript` file as you've suggested and updated the README.md for better understanding. Thus I'm closing this issue now ;-)
