### ISSUE TITLE
Support FluidMail templates

### ISSUE THREAD

**Issue by tillschweneker** [kitzberger/form-mailtext#10]
When checking the option `Use FluidEmail`, the custom mail text is not used in the email.

Is it possible to use the fluid based email templates in conjunction with the custom mail text? 

![image](https://user-images.githubusercontent.com/1279963/139681939-d15f49d7-e5e9-4a30-9737-c715edac55f6.png)

**Comment by kitzberger** [comment]
@tillschweneker, please have a go at the branch `fluid-mails` ;-)

**Comment by tillschweneker** [comment]
@kitzberger works 🚀
