### ISSUE TITLE
Missing ext-key in composer.json

### ISSUE THREAD

**Issue by helsner** [kitzberger/form-mailtext#13]
The TYPO3 extension package "kitzberger/form-mailtext", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

**Comment by kitzberger** [comment]
@helsner, Thanks! You fix has just been released as `2.1.1`.
