### ISSUE TITLE
[FEATURE] v11 compatibility 

### ISSUE THREAD

**Issue by helsner** [kitzberger/form-mailtext#15]
Will there be a v11 comp version?

**Comment by kitzberger** [comment]
@helsner, sure. But as I've not had any upgrades to 11 yet there's no actual plans for that.

Feel free to create a merge request though ;-)

**Comment by helsner** [comment]
checked with rector and extension scanner - no changes necessary besides those as it seems

**Comment by kitzberger** [comment]
@helsner, thanks for your efforts. I've just released 2.1.2!
