### ISSUE TITLE
Question: Link to uploaded files in mail text

### ISSUE THREAD

**Issue by bh-teufels** [kitzberger/form-mailtext#18]
Sorry it is more a question / feature request than an issue.

is it possible to set a link to the, in the form uploaded, files inside the mail text?

And if i use the variable of the file {fileupload-1} in the mail text i get the error Cannot convert object value of "fileupload-1" to string. how could i for example get the filename in mail text without output all by using {variables}

Thank you

**Comment by kitzberger** [comment]
@bh-teufels, I guess that's rather an EXT:form issue. It's similar to this one I've reported a year ago about multiselect fields: https://forge.typo3.org/issues/93596

I suggest you open up an issue on forge ;-)
