### ISSUE TITLE
Suggestion: Set {variables} as a default

### ISSUE THREAD

**Issue by creationell** [kitzberger/form-mailtext#20]
First of all, thank you very for this extension. It's adding great value to the TYPO3 form feature.

We'd like to suggest a change regarding solid defaults as we experienced a (kind of serious) problem after installing the extension into an existing website with numerous existing forms (because we needed the functionality for implementing a new form). After the extension was installed, the result mail sent by TYPO3 had an empty body for these forms as long as the mailtext field was empty.

This was of course an unexpected to the behavior of the existing forms which we didn't touch.

**Comment by kitzberger** [comment]
@creationell, thanks for the PR. Will release it as `2.1.3` in a minute!
