### ISSUE TITLE
If statements for singleselects doesn't function

### ISSUE THREAD

**Issue by Efdal90** [kitzberger/form-mailtext#22]
This if statement doesn't function:

{if:singleselect-1:=:}-{endif}{if:singleselect-1:=:1}Herr{endif}{if:singleselect-1:=:2}Frau{endif}{if:singleselect-1:=:3}Diverse{endif}

Have you any idea why?

**Comment by kitzberger** [comment]
:thinking: regex parsing looks good, see https://regex101.com/r/S6Yoo7/1

Maybe you can provide some more details?
* What exactly isn't working? What's the output?
* What versions of TYPO3 and extensions are you using?

**Comment by kitzberger** [comment]
@Efdal90, maybe wanna share your story? So this issue is more than just a waste of time for me? ;-)

**Comment by matthaa** [comment]
This worked for me:
Sehr {if:singleselect-1:=:Frau}geehrte Frau{endif} {if:singleselect-1:=:Herr}geehrter Herr{endif} ...
Thanks for this Extension, very helpful.
Matthias

**Comment by matthaa** [comment]
A small correction: in another project with the same configuration, this warning appears in the log when using the if statement:
```
Core: Error handler (FE): PHP Warning: Undefined array key 1 in /.../typo3conf/ext/form_mailtext/Classes/Domain/Finishers/EmailFinisher.php line 68
```
PHP 8.3
TYPO3 12.4
form_mailtext 2.1.4
Any idea? Thanks,
Matthias

**Comment by kitzberger** [comment]
Hi Matthias,
without testing it, I'd say that upgrading to 2.1.5 should fix that. It's basically this change: 8d9c679
Philipp

**Comment by matthaa** [comment]
Hi Philip,
thanks for your quick reply. Even if I modify the file accordingly, the warning persists.

**Comment by kitzberger** [comment]
What's your mail template look like? I've DM'd you on TYPO3 slack.

**Comment by matthaa** [comment]
It was my fault: I applied the [patch](https://github.com/kitzberger/form-mailtext/commit/8d9c67945d43d0dab23d06c1606f7ec3cfea6b16#diff-1d054d74de5586d389e2ac0809c77b48c3fe01d15ec91c884a6ef4d85c1b52bd) incorrectly in version 2.1.4. If you do it correctly, it works. It works fine in version 3.0.1 anyway.
