### ISSUE TITLE
[FEATURE] TYPO3 v12 compatibility

### ISSUE THREAD

**Issue by bh-teufels** [kitzberger/form-mailtext#23]
Hi there,

Just wanted to ask if there are any plans  to support TYPO3 v12 and if yes if you got a time plan for that? 

Thanks a lot!

**Comment by bh-teufels** [comment]
i made a fork https://github.com/teufelsGmbH/form-mailtext and just add 12.4 to the requirements in composer.json and ext_emconf.php
First test seems that it is working under 
TYPO3 12.4.2
PHP 8.2.2

**Comment by kitzberger** [comment]
@bh-teufels, thanks for your contribution... I'll test it later today and make a new release!

**Comment by kitzberger** [comment]
@bh-teufels, just released `2.1.4`: https://packagist.org/packages/kitzberger/form-mailtext
