### ISSUE TITLE
error in EmailFinisher when using experimental {if}

### ISSUE THREAD

**Issue by amdeu** [kitzberger/form-mailtext#26]
Hi, 
thank you for this cool extension!
I've encountered an error using the {if} control flow syntax like 

``
{if:radiobutton-1:=:value}
lorem ipsum
{endif}
``

php 8.2.2
typo3 11.5.26
form_mailtext 2.1.2
error:
``
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key 1 in /html/typo3conf/ext/form_mailtext/Classes/Domain/Finishers/EmailFinisher.php line 58 
``

To fix this, I replaced 
```
list($thenValue, $elseValue) = GeneralUtility::trimExplode('{else}', $match[4], true);
```
with
```
$thenElse = GeneralUtility::trimExplode('{else}', $match[4], true);
$thenValue = $thenElse[0];
$elseValue = $thenElse[1] ?? null;
```
in Classes/Domain/Finishers/EmailFinisher.php

**Comment by kitzberger** [comment]
@oliveoilexpert, thanks for creating the issue (and providing the solution right away!), it's fixed on `main` now...
