### ISSUE TITLE
"EXT:form_mailtext/Configuration/Form/MailtextFormSetup.yaml" could not be loaded

### ISSUE THREAD

**Issue by helmut-winkelbach** [kitzberger/form-mailtext#4]
Invalid configuration.
Invalid ext:form configuration. An error occurred while parsing file "EXT:form_mailtext/Configuration/Form/MailtextFormSetup.yaml": YAML File "EXT:form_mailtext/Configuration/Form/MailtextFormSetup.yaml" could not be loaded

**Comment by kitzberger** [comment]
@helmut-winkelbach, please specify the version of the extension and your TYPOP3 ;-)

**Comment by kitzberger** [comment]
@helmut-winkelbach in #5:
> TYPO3 Version 10.4.12 and version 2.0.1

**Comment by kitzberger** [comment]
@helmut-winkelbach, I just tested the extension with 10.4.11 *and* 10.4.12. No problems here. Can you maybe describe a little what you've done to trigger that exception?
