### ISSUE TITLE
Cannot convert array to string

### ISSUE THREAD

**Issue by bocianl** [kitzberger/form-mailtext#6]
Hello,

Thanks for a great extension. Good and very helpful work :)

I get a problem with multi-select fields, how to add this type of field to the message?

TYPO3 10.4.12

![2021-02-26_12h07_23](https://user-images.githubusercontent.com/3082489/109293097-9bef2500-782b-11eb-93bb-896c92020355.jpg)

![2021-02-26_12h11_27](https://user-images.githubusercontent.com/3082489/109293235-ce991d80-782b-11eb-95e5-68bca730933e.jpg)

**Comment by kitzberger** [comment]
@bocianl, thanks for reaching out!

I'm afraid it's not an issue of this extension but of the form extension itself. With form_mailtext deinstalled and using the marker of a multiselect field in text mail subject I get the same exception as you.

Sorry, I'm afraid to have to redirect you to the forge tracker: https://forge.typo3.org/issues/93596
