### ISSUE TITLE
Richtexteditor not showing

### ISSUE THREAD

**Issue by mkrappitz** [kitzberger/form-mailtext#7]
In your documentation screenshot there is a richtext editor. Also in the yaml config for the message field there is enableRichtext: true. In both TYPO3 9 and 10 latest with the respective latest possible version of EXT:form_mailtext there is no richt text editor for the message field in the form editor showing. See following Screenshot:

![grafik](https://user-images.githubusercontent.com/5528239/115601588-480a3500-a2de-11eb-84ad-33e378c8e481.png)

In the markup of the editor there is the following for the message field:
```html
<textarea data-random-id="" data-random-id-attribute="id" data-random-id-number="1" data-template-property="propertyPath" class="form-control" id="fe331619028799574"></textarea>
```

Any idea why that could be or what I should check?

**Comment by mkrappitz** [comment]
ok, I read the docu again and now i realized, it is only available in the plugin, not in the form editor.

**Comment by kitzberger** [comment]
@mkrappitz, thanks for reaching out. I guess I skipped the RTE in the form editor because it's only a very narrow column and the RTEs icon bar would've taken up way to much space to have an OK-ish UX.
