### ISSUE TITLE
get no output in mails

### ISSUE THREAD

**Issue by p-view** [kitzberger/form-mailtext#8]
All Mails are empty after plugin loaded. Also empty debug in $arguments['message'] in RenderMessageViewHelper.php
in typo3 9.5.24 plugin 1.0.2

**Comment by kitzberger** [comment]
@p-view, did you specify a mail text in the plugin?

**Comment by p-view** [comment]
yes, but it tested also with the default "Hi, here's the users input: {variables}"

**Comment by kitzberger** [comment]
you've got anything modified in the form configuration stack that might interfer with my extension?

**Comment by p-view** [comment]
no, i load the standart yaml from bootstrap_package

**Comment by p-view** [comment]
i have now wrote in the root setup:
```
module.tx_form.settings.yamlConfigurations.300 = EXT:form_mailtext/Configuration/Form/MailtextFormSetup.yaml
plugin.tx_form.settings.yamlConfigurations.300 = EXT:form_mailtext/Configuration/Form/MailtextFormSetup.yaml
```
now the mails come in. But onlywhen put the content overwritten inthe plugin. but thats ok. Thank you for your help. Great!

**Comment by kitzberger** [comment]
Cool, thanks for the update ;-)
